### ISSUE TITLE
Error when using client streaming

### ISSUE THREAD

**Issue by tmdoit-zz** [julien-pal/node-red-contrib-grpc#6]
```
2 Aug 14:07:51 - [error] [grpc-client-streaming:aaa] aaaaaddTypeError: node.call.write is not a function
TypeError: node.call.write is not a function
    at gClientStreamingNode.<anonymous> (/data/node_modules/node-red-contrib-grpc/grpc/grpc-client-streaming.js:69:31)
    at emitOne (events.js:116:13)
    at gClientStreamingNode.emit (events.js:211:7)
    at gClientStreamingNode.Node.receive (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:237:14)
    at InjectNode.Node.send (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:159:22)
    at InjectNode.<anonymous> (/usr/src/node-red/node_modules/@node-red/nodes/core/core/20-inject.js:78:26)
    at emitOne (events.js:116:13)
    at InjectNode.emit (events.js:211:7)
    at InjectNode.Node.receive (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:237:14)
    at /usr/src/node-red/node_modules/@node-red/nodes/core/core/20-inject.js:117:22
```
Node-RED shows that node is connected to the server.
What more information do you need, I can export flow and make server available.

**Comment by jeff-bonevich** [comment]
I can reproduce this error.  In general the stream support in the plugin does not seem to work.  Flow file attached.
[streaming.txt](https://github.com/julien-pal/node-red-contrib-grpc/files/6281884/streaming.txt)

**Comment by drehermi** [comment]
would a pull request be accepted if I could provide a fix?

I mean maybe it is working as described in the documentation but for streaming I need to keep a long running stream (like audio streaming) and messages should just be output when they arrive and not be buffered because the only reason why the stream ends is when the system shuts down.

This means it would be a different operating mode then the one in the documenation: "_This node opens a gRPC request, expects the streaming content at payload and returns the response if the stream is closed._" which I would consider more something like a file download.
